name: Resolve which editions should build
inputs:
  release-type:
    description: EE, OS, ALL etc
    type: choice
    options:
      - ALL
      - OSS
      - EE
    required: true
outputs:
  should_build_oss:
    value: ${{ steps.resolve-editions.outputs.should_build_oss }}
  should_build_ee:
    value: ${{ steps.resolve-editions.outputs.should_build_ee }}
runs:
  using: "composite"
  steps:
    - shell: bash
      id: resolve-editions
      run: |
        source ${GITHUB_ACTION_PATH}/build.functions.sh

        echo "should_build_oss=$(should_build_oss "${RELEASE_TYPE}")" >> ${GITHUB_OUTPUT}
        echo "should_build_ee=$(should_build_ee "${RELEASE_TYPE}")" >> ${GITHUB_OUTPUT}
      env:
        RELEASE_TYPE: ${{ inputs.release-type }}
