name: Get supported JDKs
description: Get supported JDKs
inputs:
  HZ_VERSION:
    description: HZ Version (e.g. 5.4.0)
    required: true
outputs:
  jdks:
    value: ${{ steps.get-supported-jdks.outputs.jdks }}
    description: Returns supported JDKs
  default-jdk:
    value: ${{ steps.get-default-jdk.outputs.default-jdk }}
    description: Returns default JDK
runs:
  using: "composite"
  steps:
    - shell: bash
      id: get-supported-jdks
      run: |
        source ${GITHUB_ACTION_PATH}/get-supported-jdks.functions.sh
        echo "jdks=$(get_supported_jdks ${HZ_VERSION} )" >> ${GITHUB_OUTPUT}
      env:
        HZ_VERSION: ${{ inputs.HZ_VERSION}}

    - shell: bash
      id: get-default-jdk
      run: |
        echo "default-jdk=$(jq --raw-output '.[-1]' <<< '${{ steps.get-supported-jdks.outputs.jdks }}')" >> ${GITHUB_OUTPUT}
