name: Test image size
description: Test image isn't excessively large / wasting space

inputs:
  image:
    description: Image name to test
    required: true
  minimum_efficiency:
    description: Minimum efficiency percentage required - 0-1 scale
    required: false
    default: 0.8

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        . ${GITHUB_ACTION_PATH}/assert-image-size.functions.sh

        assert_image_size "${IMAGE}" "${MINIMUM_EFFICIENCY}"
      env:
        IMAGE: ${{ inputs.image }}
        MINIMUM_EFFICIENCY: ${{ inputs.minimum_efficiency }}
