name: Get supported platforms
inputs:
  dockerfile:
    description: Path of the Dockerfile used to determine the base image from
    required: true
  jdk:
    description: The JDK version
    required: true
outputs:
  platforms:
    description: Comma-separated string in a form suitable for supplying to Docker
    value: ${{ steps.get-supported.outputs.platforms }}
runs:
  using: "composite"
  steps:
    - shell: bash
      id: get-supported
      run: |
        . ${GITHUB_ACTION_PATH}/../.github/scripts/logging.functions.sh
        . ${GITHUB_ACTION_PATH}/../.github/scripts/dockerfile.functions.sh

        base_image_name=$(get_base_image_name ${DOCKERFILE})

        case "${base_image_name}" in
            *"alpine"*)
              PLATFORMS="linux/arm64,linux/amd64,linux/s390x"
              # already fixed on alpine:edge, probably will be released in alpine:3.20
              if [[ "${JDK}" -lt 17 ]]; then
                PLATFORMS="${PLATFORMS},linux/ppc64le"
              fi
              echo "platforms=${PLATFORMS}" >> ${GITHUB_OUTPUT}
            ;;
            *"ubi"*)
              echo "platforms=linux/arm64,linux/amd64,linux/s390x,linux/ppc64le" >> ${GITHUB_OUTPUT}
            ;;
            *)
            echoerr "Unsupported platform behaviour for ${base_image_name}" ; return 1
            ;;
        esac
      env:
        DOCKERFILE: ${{ inputs.dockerfile }}
        JDK: ${{ inputs.JDK }}
