name: Slack notification
inputs:
  slack-webhook-url:
    description: Slack webhook url
    required: true
  slack-channel:
    description: Slack channel to send the notification to
    default: "#hazelcast-docker-notifications"
  status:
    description: The status to set, otherwise inherited from the enclosing job
    required: false
runs:
  using: "composite"
  steps:
    - id: compute
      shell: bash
      run: |
        echo "status=${STATUS}" >> ${GITHUB_OUTPUT}

        JOB_URL=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

        if [[ "${STATUS}" == "success" ]]; then
          echo "text=✅ \`${{ github.workflow }}\` (\`${{ github.workflow_ref }}\`)\n${JOB_URL}" >> ${GITHUB_OUTPUT}
        else
          echo "text=❌ \`${{ github.workflow }}\` (\`${{ github.workflow_ref }}\`) - ${STATUS}\n${JOB_URL}" >> ${GITHUB_OUTPUT}
        fi
      env:
        STATUS: ${{ inputs.status || job.status }}

    - uses: slackapi/slack-github-action@af78098f536edbc4de71162a307590698245be95 # v3.0.1
      with:
        webhook: ${{ inputs.slack-webhook-url }}
        webhook-type: incoming-webhook
        payload: |
          channel: "${{ inputs.slack-channel }}"
          text: "${{ steps.compute.outputs.text }}"
