name: Get JFrog credentials
inputs:
  aws-role-to-assume:
    description: 'AWS Role to assume for accessing secrets'
    required: true
  jfrog-oidc-provider-name:
    description: 'JFrog provider to authenticate against'
    required: true
outputs:
  url:
    value: ${{ steps.get-url.outputs.url }}
  user:
    value: ${{ steps.jfrog.outputs.oidc-user }}
  token:
    value: ${{ steps.jfrog.outputs.oidc-token }}
runs:
  using: "composite"
  steps:
    - uses: aws-actions/configure-aws-credentials@v5
      with:
        role-to-assume: ${{ inputs.aws-role-to-assume }}
        aws-region: 'us-east-1'

    - uses: aws-actions/aws-secretsmanager-get-secrets@v2
      with:
        # Make them quasi-unique to avoid overlapping with other secrets that may exist in the calling workflow
        # Workaround lack of https://github.com/aws-actions/aws-secretsmanager-get-secrets/issues/14
        secret-ids: |
          GET_JFROG_CREDENTIALS_JFROG,JFROG
        parse-json-secrets: true

    - id: get-url
      shell: bash
      run: |
        echo "url=${GET_JFROG_CREDENTIALS_JFROG_URL}" >> ${GITHUB_OUTPUT}

    - id: jfrog
      uses: jfrog/setup-jfrog-cli@v4
      env:
        JF_URL: https://${{ env.GET_JFROG_CREDENTIALS_JFROG_URL }}
      with:
        oidc-provider-name: ${{ inputs.jfrog-oidc-provider-name }}
