name: Check base image outdated
description: Check if the base image or system packages are outdated

inputs:
  ref:
    description: hazelcast-docker branch to check
    required: true
  image-name:
    description: Name of the image (e.g. hazelcast/hazelcast:5.5.0-slim)
    required: true
  dockerfile-path:
    description: Path to the dockerfile (e.g. hazelcast-enterprise/Dockerfile)
    required: true

outputs:
  outdated:
    description: If the specified image is outdated
    value: ${{ steps.check.outputs.outdated }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v5
      with:
        repository: hazelcast/hazelcast-docker
        ref: ${{ inputs.ref }}
        path: hazelcast-docker

    - shell: bash
      id: check
      run: |
        . ${GITHUB_ACTION_PATH}/../.github/scripts/logging.functions.sh
        pushd ${GITHUB_ACTION_PATH}/..
          . check-base-images/check-base-images.functions.sh
        popd

        echodebug "Checking ${IMAGE}"
        if base_image_outdated_from_dockerfile "${IMAGE}" "${DOCKERFILE}"; then
          echo "outdated=true" >> ${GITHUB_OUTPUT}
          echonotice "${IMAGE} needs rebuild"
        elif packages_updatable_from_dockerfile "${IMAGE}" "${DOCKERFILE}"; then
          echo "outdated=true" >> ${GITHUB_OUTPUT}
          echonotice "System package upgrades for ${IMAGE} available"
        else
          echo "outdated=false" >> ${GITHUB_OUTPUT}
          echodebug "${IMAGE} is up-to-date"
        fi
      env:
        IMAGE: ${{ inputs.image-name }}
        DOCKERFILE: hazelcast-docker/${{ inputs.dockerfile-path }}
