name: Which editions should build
inputs:
  release-type:
    description: EE, OS, ALL etc
    type: choice
    options:
      - ALL
      - OSS
      - EE
    required: true
outputs:
  should_build_oss:
    value: ${{ steps.which_editions.outputs.should_build_oss }}
  should_build_ee:
    value: ${{ steps.which_editions.outputs.should_build_ee }}
runs:
  using: "composite"
  steps:
    - shell: bash
      id: which_editions
      run: |
        source ${{ github.action_path }}/build.functions.sh

        echo "should_build_oss=$(should_build_oss "${{ inputs.release-type }}")" >> ${GITHUB_OUTPUT}
        echo "should_build_ee=$(should_build_ee "${{ inputs.release-type }}")"" >> ${GITHUB_OUTPUT}
