name: Setup Hazelcast Versions
description: Sets up OSS and EE Hazelcast version variables.


inputs:
  working-directory:
    description: Directory containing hazelcast-oss and hazelcast-enterprise directories
    required: false
    default: .

outputs:
  HZ_VERSION:
    description: Hazelcast version
    value: ${{ steps.get_docker_vars.outputs.HZ_VERSION }}
  LAST_RELEASED_HZ_VERSION_OSS:
    description: Last released Hazelcast OSS version
    value: ${{ steps.get_maven_vars.outputs.LAST_RELEASED_HZ_VERSION_OSS }}

runs:
  using: "composite"
  steps:
    - name: Get Dockerfile variables
      id: get_docker_vars
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        . ${{ github.action_path }}/../.github/scripts/logging.functions.sh

        get_hz_version() {
          local dockerfile=$1
          awk -F '=' '/^ARG HZ_VERSION=/ {print $2}' ${dockerfile}
        }

        HZ_VERSION_OSS=$(get_hz_version hazelcast-oss/Dockerfile)
        HZ_VERSION_EE=$(get_hz_version hazelcast-enterprise/Dockerfile)

        if [[ "${HZ_VERSION_OSS}" == "${HZ_VERSION_EE}" ]]; then
          echo "HZ_VERSION=${HZ_VERSION_OSS}" >> ${GITHUB_OUTPUT}
        else
          echoerr "Versions extracted from Dockerfile(s) do not match (${HZ_VERSION_OSS} / ${HZ_VERSION_EE})!"
          exit 1
        fi

    - name: Get Maven variables
      id: get_maven_vars
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        source /dev/stdin <<< "$(curl --silent https://raw.githubusercontent.com/hazelcast/hazelcast-docker/master/hazelcast-oss/maven.functions.sh)"
        LAST_RELEASED_HZ_VERSION_OSS="$(get_latest_version com.hazelcast hazelcast-distribution https://repo.maven.apache.org/maven2)"
        echo "LAST_RELEASED_HZ_VERSION_OSS=$LAST_RELEASED_HZ_VERSION_OSS" >> ${GITHUB_OUTPUT}
