name: Test which-editions action

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test scripts
        run: ./which-editions/test_scripts.sh
