name: Test verify-docker-reproducibility action

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Test scripts
        run: ./verify-docker-reproducibility/test_scripts.sh

      - name: Run verify-docker-reproducibility
        uses: ./verify-docker-reproducibility
        with:
          dockerfile: verify-docker-reproducibility/test-data/reproducible.Dockerfile
          extra-args: verify-docker-reproducibility/test-data
