name: Test get-supported-jdks action

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-slim
    strategy:
      fail-fast: false
      matrix:
        include:
          - hz-version: 4.2.8
            expected-jdks: "['11', '17']"
            expected-default-jdk: 17

          - hz-version: 5.3.8
            expected-jdks: "['11', '17']"
            expected-default-jdk: 17

          - hz-version: 5.3.99
            expected-jdks: "['11', '17']"
            expected-default-jdk: 17

          - hz-version: 5.4.0
            expected-jdks: "['17', '21']"
            expected-default-jdk: 21

          - hz-version: 5.4.1
            expected-jdks: "['17', '21']"
            expected-default-jdk: 21

          - hz-version: 5.5.0
            expected-jdks: "['17', '21']"
            expected-default-jdk: 21

          - hz-version: 5.7.0
            expected-jdks: "['17', '21', '25']"
            expected-default-jdk: 25

          - hz-version: 5.7.0-SNAPSHOT
            expected-jdks: "['17', '21', '25']"
            expected-default-jdk: 25

          - hz-version: 6.0.0
            expected-jdks: "['17', '21', '25']"
            expected-default-jdk: 25

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Run get-supported-jdks
        id: jdks
        uses: ./get-supported-jdks
        with:
          HZ_VERSION: ${{ matrix.hz-version }}

      - name: Test
        run: |
          set -o errexit -o nounset -o pipefail ${RUNNER_DEBUG:+-x}
          source /dev/stdin <<< "$(curl --silent https://raw.githubusercontent.com/hazelcast/assert.sh/main/assert.sh)"

          assert_eq \
            "${EXPECTED_JDKS}" \
            "$ACTUAL_JDKS" \
            "For ${HZ_VERSION} jdks should be ${EXPECTED_JDKS}"

          assert_eq \
            "${EXPECTED_DEFAULT_JDK}" \
            "${ACTUAL_DEFAULT_JDK}" \
            "For ${HZ_VERSION} default jdk should be ${EXPECTED_DEFAULT_JDK}"
        env:
          HZ_VERSION: ${{ matrix.hz-version }}
          EXPECTED_JDKS: ${{ matrix.expected-jdks }}
          ACTUAL_JDKS: ${{ steps.jdks.outputs.jdks }}
          EXPECTED_DEFAULT_JDK: ${{ matrix.expected-default-jdk }}
          ACTUAL_DEFAULT_JDK: ${{ steps.jdks.outputs.default-jdk }}
