name: Test download-hz-dist action

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    strategy:
      matrix:
        distribution:
          - hazelcast
          - hazelcast-enterprise
        version:
          - 5.1
          - 5.6.1-SNAPSHOT
        classifier:
          - slim
          - ''
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Download "${{ matrix.distribution }}"
        uses: ./download-hz-dist
        id: download
        with:
          environment: live
          aws-role-to-assume: ${{ vars.AWS_HAZELCAST_OIDC_GITHUB_ACTIONS_ROLE_ARN }}
          distribution: "${{ matrix.distribution }}"
          hz_version: "${{ matrix.version }}"
          classifier: "slim"
          packaging: "tar.gz"

      - name: Check file downloaded from `${{ steps.download.outputs.download_url }}`
        run: |
          if [[ ! -f "${{ steps.download.outputs.output_file }}" ]]; then
            echo "${{ steps.download.outputs.output_file }} not found!"
            exit 1
          fi

          # https://stackoverflow.com/a/2001750
          if ! tar --list --gzip --file ${{ steps.download.outputs.output_file }} > /dev/null; then
            echo "${{ steps.download.outputs.output_file }} not valid!"
            exit 1
          fi
