name: Test resolve-editions action

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test scripts
        run: ./resolve-editions/test_scripts.sh

      - name: Run resolve-editions
        id: resolve-editions
        uses: ./resolve-editions
        with:
          release-type: OSS

      - name: Test
        run: |
          set -o errexit -o nounset -o pipefail ${RUNNER_DEBUG:+-x}
          source /dev/stdin <<< "$(curl --silent https://raw.githubusercontent.com/hazelcast/assert.sh/main/assert.sh)"

          TESTS_RESULT=0
          
          assert_equals() {
            local release_type=$1
            local expected=$2
            local actual=$3
            local msg="should_build for ${release_type} should be equal to ${expected}"
            assert_eq "$expected" "$actual" "$msg" && log_success "$msg" || TESTS_RESULT=$?
          }
          
          assert_equals "should_build_oss" "yes" "${{ steps.resolve-editions.outputs.should_build_oss }}"
          assert_equals "should_build_ee" "no" "${{ steps.resolve-editions.outputs.should_build_ee }}"

          assert_eq 0 "$TESTS_RESULT" "All tests should pass"
